version: '3.8'

services:
  # The Database Service
  mysql_db:
    image: mysql:8.0
    container_name: task_manager_db
    restart: always
    environment:
      MYSQL_DATABASE: project_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # The Visual Interface (Bonus tool)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: task_manager_pma
    links:
      - mysql_db
    environment:
      PMA_HOST: mysql_db
      PMA_PORT: 3306
    ports:
      - "8081:80"

volumes:
  db_data: